### ISSUE TITLE
Regarding errorbars on the data

### ISSUE THREAD

**Issue by JonahDW** [tholoien/XDGMM#39]
Dear Devs,

I've been recently working with your implementation of XDGMM, performing density estimation of noisy data. So far I really like the models that are coming out, but it is when scoring samples of new data points that some (for me) unexpected things happen. I noticed that when the specified points would have somewhat larger errorbars, they would systematically get assigned much lower values by score_samples compared to those data points with similar parameter values. 

I was wondering if you could provide some insight into how these errors are treated in the method, as they seemed to be weighed quite heavily from what I have seen. 

Thanks in advance!

**Comment by tholoien** [comment]
Apologies for the very long delay in responding to this. Not sure if a response is still helpful, but will comment in case others have similar questions in the future.

The scikit-learn GMM has a built-in score_samples method that can be used for scoring the data in a dataset. It does not, however, have the functionality to include error bars on the data, which is one reason why our XDGMM is useful. Our score_samples method folds the error bars into the covariance matrix for a skl GMM object and then uses the built-in score_samples method to calculate the score in order to include the errors in the scoring. Larger errorbars should thus result in lower scores, though the amount that the error bars affect the scores would be dependent on the model and dataset.
